###
GET https://expensive-tights-fly.cyclic.app/
### GET DEVICE 
GET http://localhost:5000/device

### GET DEVICE BY ID
GET http://localhost:5000/device/653f5c8b5288015e74c29c7d

### POST DEVICE 
POST http://localhost:5000/device
Content-Type: application/json

{
    "name" : "saklar",
    "value" : true
}

### UPDATE DEVICE 
PUT http://localhost:5000/device/653f5c8b5288015e74c29c7d
Content-Type: application/json

{
    "name" : "saklar",
    "value" : false
}

### UPDATE DEVICE 
DELETE http://localhost:5000/device/653f512c0be39bf843106fab
Content-Type: application/json

### GET SENSOR 
GET http://localhost:5000/sensor

### GET SENSOR BY ID
GET http://localhost:5000/sensor/653f5da3a13396104e5bbcc6

### POST SENSOR
POST http://localhost:5000/sensor
Content-Type: application/json

{
    "name" : "LDR",
    "value" : 500
}

### UPDATE SENSOR
PUT http://localhost:5000/sensor/653f5da3a13396104e5bbcc6
Content-Type: application/json

{
    "name" : "LDR",
    "value" : 300
}

### UPDATE SENSOR
DELETE http://localhost:5000/sensor/653f5da3a13396104e5bbcc6
Content-Type: application/json